shallow_clone: true
environment:
  global:
    STACK_ROOT: c:\s
    MSYS: msys64
  matrix:
  - PLATFORM: x64
    MINGW: mingw64
    MINGW_PACKAGE_PREFIX: mingw-w64-x86_64
    STACK_ARCH: x86_64
  - PLATFORM: x86
    MINGW: mingw32
    MINGW_PACKAGE_PREFIX: mingw-w64-i686
    STACK_ARCH: i386
cache:
- c:\s -> appveyor.yml
- c:\msys64\var\cache\pacman\pkg -> appveyor.yml
install:
- set HOME=.
- set "PATH=c:\%MSYS%\%MINGW%\bin;c:\%MSYS%\usr\bin;%PATH%"
- echo %PATH%
- curl -ostack.zip -LsS --insecure https://www.stackage.org/stack/windows-%STACK_ARCH%
- 7z x stack.zip stack.exe
- stack setup > nul
- pacman --noconfirm --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel
- pacman --noconfirm -Syuu
- pacman --noconfirm -Suu
- pacman --noconfirm -S %MINGW_PACKAGE_PREFIX%-pkg-config %MINGW_PACKAGE_PREFIX%-gtk2
- pacman --noconfirm -Sc
build_script:
- stack --no-terminal build --skip-msys --only-dependencies
- stack --no-terminal build --skip-msys --ghc-options -Werror
test_script:
- stack sdist
- threadscope --version
version: '{build}'
