version: "{build}"
shallow_clone: true
clone_folder: "c:/WORK"

platform: x64

environment:
  global:
    APPVEYOR_SAVE_CACHE_ON_ERROR: true
    CABOPTS: "--store-dir=c:/SR --http-transport=plain-http"
  matrix:
  - GHCVER: "8.8.1"
  - GHCVER: "8.6.5"
  - GHCVER: "8.4.4"
  - GHCVER: "8.2.2"

cache:
- "c:/SR"

install:
- "choco install -y ghc --version %GHCVER%"
- "refreshenv"
- "set PATH=C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin;%PATH%"
- "pacman --noconfirm -Sy mingw-w64-x86_64-gtk2"
- "cabal --version"
- "ghc --version"
- "cabal %CABOPTS% update -vverbose+nowrap"

build_script:
- cat cabal.project
- "cabal %CABOPTS% new-build -vnormal+nowrap --dry all"
- ps: "Push-AppveyorArtifact dist-newstyle\\cache\\plan.json"
- "cabal %CABOPTS% new-build -j -vnormal+nowrap all --dep"

test_script:
- "cabal %CABOPTS% new-build -j1 -vnormal+nowrap all"

after_test:
- bash -c "cp -v $(find -name threadscope.exe) ./threadscope.exe"
- 7z a threadscope.windows.%PLATFORM%.ghc-%GHCVER%.zip threadscope.exe
- ps: "Push-AppveyorArtifact threadscope.windows.$($env:PLATFORM).ghc-$($env:GHCVER).zip"

deploy:
- provider: GitHub
  auth_token:
    secure: IbU7Tokqkdq4bI5PT+HvzG0hO4O8t2Lxq3GamSuAzWsQWt4vZahOGL9StxIXIe94
  artifact: threadscope.windows.$(platform).ghc-$(GHCVER).zip
  release: $(appveyor_repo_tag_name)
  on:
    appveyor_repo_tag: true
    GHCVER: "8.8.1"
