platform: x64
shallow_clone: true
environment:
  global:
    STACK_ROOT: c:\sr
cache:
- '%APPDATA%\cabal'
- c:\msys64\var\cache\pacman\pkg -> appveyor.yml
install:
- set HOME=.
- choco install ghc
- c:\ProgramData\chocolatey\bin\RefreshEnv
- set "PATH=%AppData%\local\bin;c:\msys64\mingw64\bin;c:\msys64\usr\bin;%PATH%"
- pacman --noconfirm -Syu
- pacman --noconfirm -Suu
- pacman --noconfirm -S mingw-w64-x86_64-pkg-config mingw-w64-x86_64-gtk2
- pacman --noconfirm -Sc
- mkdir -p %APPDATA%\local\bin
- ps: Start-FileDownload 'https://ci.appveyor.com/api/buildjobs/rqo8q29y9ivh9c6l/artifacts/cabal-install%2Fdist%2Fbuild%2Fcabal%2Fcabal.exe' -FileName "$env:APPDATA\local\bin\cabal.exe"
- cabal update
- cabal --version
build_script:
- cabal new-build --only-dependencies
test_script:
- cabal new-build --ghc-options -Werror
version: '{build}'
